name: flutter_media_storage
description: A simple package to download and store/persist media in flutter apps.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4           #? Needed to download the contents from a given url.
  path_provider: ^2.0.11  #? Needed to access the required path to perists data on iOS and Android.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
